const colors = {
  light: {
    text: "#f8fafc",
    tint: "#6366f1",
    background: "#020617",
    foreground: "#f8fafc",
    card: "#0f172a",
    cardForeground: "#f8fafc",
    primary: "#6366f1",
    primaryForeground: "#ffffff",
    secondary: "#1e293b",
    secondaryForeground: "#f8fafc",
    muted: "#1e293b",
    mutedForeground: "#94a3b8",
    accent: "#a855f7",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e293b",
    input: "#1e293b",
  },
  dark: {
    text: "#f8fafc",
    tint: "#6366f1",
    background: "#020617",
    foreground: "#f8fafc",
    card: "#0f172a",
    cardForeground: "#f8fafc",
    primary: "#6366f1",
    primaryForeground: "#ffffff",
    secondary: "#1e293b",
    secondaryForeground: "#f8fafc",
    muted: "#1e293b",
    mutedForeground: "#94a3b8",
    accent: "#a855f7",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e293b",
    input: "#1e293b",
  },
  radius: 12,
};

export default colors;
